[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg"]

# 1. API routes -> serverless functions (must be first!)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 2. Don't redirect static assets (css, js, images, fonts)
[[redirects]]
  from = "/:file.:ext"
  to = "/:file.:ext"
  status = 200

# 3. SPA routing (all other paths go to index.html)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
