[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg"]
  directory = "functions"

# redirect /api/* → serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# optional global headers (CORS + basic security)
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[scheduled_functions]
  # run every day at 00:00 UTC
  prices_auto = "0 0 * * *"
