[build]
  # no build step since you're serving raw HTML/JS/CSS
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg"]

# API routes -> serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA routing: always serve index.html for non-file routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# optional security headers
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

# scheduled function (daily price update)
[[scheduled]]
  cron = "0 0 * * *"
  command = "prices_auto"
