[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg"]

# 1. API routes -> serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 2. Let Netlify serve static assets directly (no redirect for real files)
[[redirects]]
  from = "/:file.:ext"
  to = "/:file.:ext"
  status = 200

[[redirects]]
  from = "/:file/:filename.:ext"
  to = "/:file/:filename.:ext"
  status = 200

# 3. SPA routing: all other routes go to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# security headers
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

# scheduled job
[[scheduled]]
  cron = "0 0 * * *"
  command = "prices_auto"
